"""empty message

Revision ID: 771733a34ad4
Revises: 7c12194d4796
Create Date: 2024-01-08 16:15:33.363864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771733a34ad4'
down_revision = '7c12194d4796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
